all:
	(cd corrosion; rpmbuild --define "%source_date_epoch_from_changelog 0" -bb uncloud-corrosion.spec && rm -rf ~/rpmbuild)
	(cd uncloudd; rpmbuild --define "%source_date_epoch_from_changelog 0" -bb uncloudd.spec && rm -rf ~/rpmbuild)

clean:
	git clean -f -d
